### ISSUE TITLE
CODE domain variable change from 21.11.3.6 

### ISSUE THREAD

**Issue by sebtiz13** [chrisingenhaag/helm#10]
Hello from CODE version 21.11.3.6 the variable `domain` has been changed in `aliasgroupX` and throw an error if is not defined.
[see CODE changes](https://sdk.collaboraonline.com/docs/installation/CODE_Docker_image.html#id3)

For the moment I have clone this charts and I have replace the env variable `domain` by `aliasgroup1` to get a functional deployment, but I haven't real idea how manage this properly in the chart.

**Comment by chrisingenhaag** [comment]
Hi @sebtiz13 , 
I just created a branch for this. Pls take a look to #11

**Comment by sebtiz13** [comment]
It's work perfectly. Thanks for your speed
