### ISSUE TITLE
Google Chrome issue

### ISSUE THREAD

**Issue by letmagnau** [chrisingenhaag/helm#17]
HI @chrisingenhaag 

I'm trying to use your chart to integrate CODE on  my project.
I'm experimenting a little problem when I use Google Chrome

it seems to be not able to do  synchronous call inside Cool.html

Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://app.test.synbee.it/browser/eb73aa3/l10n/uno-localizations.json'.
    at request_JSON (https://app.test.synbee.it/browser/eb73aa3/bundle.js:1:766277)
    at String_ctr.<computed> (https://app.test.synbee.it/browser/eb73aa3/bundle.js:1:766621)
    at https://app.test.synbee.it/browser/eb73aa3/bundle.js:1:770033
    at https://app.test.synbee.it/browser/eb73aa3/bundle.js:1:770592

    , request_JSON = function(uri) {
        if (browserless)
            return loadFromDisk(uri);
        var req = new XHR
          , data = {};
        req.open("GET", uri, FALSE);    <<-- HERE (if I put TRUE = a horrible local variable with value !0 ... it start correctly
        req.send(null);     
        try {
            data = JSON.parse(req.responseText)
        } catch (e) {
            setTimeout(function() {
                var l10n_err = new Error("Unable to load localization data: " + uri);
                l10n_err.name = "Localization Error";
                throw l10

any indication about this behavior? 

If I use Mozilla Firefox ..all goes in the correct way

regards

**Comment by chrisingenhaag** [comment]
Hi @letmagnau ,
I think you have to talk to the developers of collabora. Maybe here https://github.com/CollaboraOnline/online . This is just a helm chart for the docker container.

Cheers
