### ISSUE TITLE
Allow using an existing secret for admin pannel

### ISSUE THREAD

**Issue by sashokbg** [chrisingenhaag/helm#19]
Hello,

Instead of putting the username and password in the helm values file, we can use a reference to an existing secret.

I have opened a PR that covers this new feature.

#18 

Please let me know what you think :)

Best Regards,
Alexander

**Comment by chrisingenhaag** [comment]
Yes, it´s good practice to allow existingSecret

**Comment by chrisingenhaag** [comment]
closed via #18
