### ISSUE TITLE
Changeing of Helm Config does not restart pod

### ISSUE THREAD

**Issue by genofire** [chrisingenhaag/helm#20]
After the Helm-Chart reconfigure the ConfigMap, the Pod is not restartet.

A Solution could be, that the ConfigMap-Name becomes a hash.

https://github.com/kubernetes/kubernetes/issues/22368#issuecomment-790858402

Here a snipped:
```
name: configmap-{{ .Values.collabora | toYaml | sha256sum | trunc 8 }}
```

**Comment by chrisingenhaag** [comment]
I created a PR for this. But I rather would create a hash of the existing configmap instead of add the hash to the configmap name itself.
So configmap name stays and changes over time. But one can rollback to previous releases including rollback of the configmap.
