### ISSUE TITLE
Allow DONT_GEN_SSL_CERT to be a string

### ISSUE THREAD

**Issue by BertrandGouny** [chrisingenhaag/helm#9]
Hello,

thanks a lot for the chart :)

not sure why but my configuration only works with 
`
DONT_GEN_SSL_CERT: set
`
that is not allowed by helm because DONT_GEN_SSL_CERT is defined as a boolean.

I tried with DONT_GEN_SSL_CERT: false but it don't work either.

Is it possible to change DONT_GEN_SSL_CERT to accept any string ? Not sure what are the possible drawback.

**Comment by BertrandGouny** [comment]
i managed to make it work with DONT_GEN_SSL_CERT: true, feel free to close this issue

**Comment by chrisingenhaag** [comment]
ok
